### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by OniWithTheHoodie** [OniWithTheHoodie/your-tribe-for-life-squad-page#1]
Design squad page maken voor woensdag

**Comment by itsValyria** [comment]
![Untitled_Artwork](https://github.com/user-attachments/assets/da106641-cc3c-4a45-b5e8-56d245b11b64)

**Comment by RukiyaTossou** [comment]
![image](https://github.com/user-attachments/assets/55efc5c4-3ce2-4756-9476-3dcc78a84e8a)

**Comment by Akikosophia** [comment]
![Media](https://github.com/user-attachments/assets/bac3e924-10f7-4fa6-bf89-3209426919ea)
