### ISSUE TITLE
Inspiratie opdoen voor detail page

### ISSUE THREAD

**Issue by itsValyria** [OniWithTheHoodie/your-tribe-for-life-squad-page#14]

**Comment by Akikosophia** [comment]
https://www.figma.com/design/R4hylHYnKXGfit6t7KFIS8/your-tribe-for-life-squad-page?node-id=0-1&node-type=canvas&t=cVch618Zx2mrNSPz-0

Inspiratie moodboard

![Image](https://github.com/user-attachments/assets/79175a0d-1ffd-4f70-8eb9-a1fe2fedb3c8)
