### ISSUE TITLE
Designs maken voor de detailpagina

### ISSUE THREAD

**Issue by Akikosophia** [OniWithTheHoodie/your-tribe-for-life-squad-page#17]

**Comment by Akikosophia** [comment]
Screenshots van het designs kunnen in de comments

**Comment by RukiyaTossou** [comment]
Design voor onze detailpagina (mobile) 

![Image](https://github.com/user-attachments/assets/7c64422c-fc70-47b7-b779-c8b02a3efded)

**Comment by Akikosophia** [comment]
![Image](https://github.com/user-attachments/assets/49146d18-0025-470e-ad2b-fe78bdec862c)

**Comment by zainablfz** [comment]
Mobile versie van het design van de detailpagina. 

![Image](https://github.com/user-attachments/assets/069f6689-dd4d-448f-846b-c76b281bcb73)

**Comment by Akikosophia** [comment]
![Image](https://github.com/user-attachments/assets/52a15983-780c-4bf6-ae89-285c36d1e6b9)

**Comment by RukiyaTossou** [comment]
Final design (meest linker)

![Image](https://github.com/user-attachments/assets/4ba48f8c-dac7-4482-ab74-4201766c76a2)
