### ISSUE TITLE
Dit bestand mag weg...

### ISSUE THREAD

**Issue by ju5tu5** [OniWithTheHoodie/your-tribe-for-life-squad-page#19]
https://github.com/OniWithTheHoodie/your-tribe-for-life-squad-page/blob/6443389e8a43d2d77a3481e67530de3ef483d94f/src/app.d.ts#L1

**Comment by OniWithTheHoodie** [comment]
bestand is verwijderd

old
![image](https://github.com/user-attachments/assets/8d1f6d0d-2237-479d-ad56-7b17bd0c4e0e)
new
![image](https://github.com/user-attachments/assets/8858e514-e2a4-4ff5-8899-721d542b5f72)

**Comment by OniWithTheHoodie** [comment]
has been solved
